@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body['access_token']}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diegol@teste.com",
  "password": "123545",
  "role": "DELIVERED_DRIVER",
  "latitude": "854512121575",
  "longitude": "-84545486624",
  "phone": "11XXXXXX51"
}

### @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "jose@teste.com",
  "password": "123545"
}

###

# @name create_package
POST {{baseUrl}}/packages
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Pacote 04 Exemplo",
  "content": "Contéudo exemplo",
  "status": "delivered",
  "recipientId": "bda0f0d5-3ee5-424e-8dd9-f5ed48efa4ed",
  "delivererId": "2af0fcf2-1084-47dc-b3f4-6ec9235f71ec",
  "latitude": "548841515154862",
  "longitude": "-88745151521563"
}

###

# @name delete_delivered_driver

DELETE {{baseUrl}}/delivered-driver/e324c8ef-bf60-463b-b907-9eee49c03674