@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body['access_token']}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jose Santos",
  "email": "jose@teste.com",
  "password": "123545",
  "role": "DELIVERED_DRIVER",
  "latitude": "fdrfdcd8545dc1",
  "longitude": "sdsdsxcsxcsxw",
  "phone": "42XXXXXX85"
}

### @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "jose@teste.com",
  "password": "123545"
}

###

# @name create_package
POST {{baseUrl}}/packages
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Pacote 04 Exemplo",
  "content": "Contéudo exemplo",
  "status": "delivered",
  "recipientId": "efe981a3-7ff2-45fe-ba29-2b1b790e252c",
  "delivererId": "10512ca7-94c4-4786-ac4c-480d0326b1ad"
}

###

# @name delete_delivered_driver

DELETE {{baseUrl}}/delivered-driver/e324c8ef-bf60-463b-b907-9eee49c03674