@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Pedro Almeida",
  "email": "pedro@teste.com",
  "password": "123545",
  "role": "delivered_driver"
}

###

# @name create_package

POST {{baseUrl}}/packages
Content-Type: application/json

{
  "title": "Pacote 01 Exemplo",
  "content": "Contéudo exemplo",
  "status": "delivered",
  "recipientId": "efe981a3-7ff2-45fe-ba29-2b1b790e252c",
  "delivererId": "10512ca7-94c4-4786-ac4c-480d0326b1ad"
}